[build-system]
requires = ['setuptools', 'setuptools-scm', 'wheel']
build-backend = "setuptools.build_meta"

[project]
name = "nba"
version = "0.1.0"
description = "Python project used for NBA statistics analysis"

[tool.setuptools]
packages = ["nba"]
